services:
  - type: web
    name: chat-frontend
    env: static
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    buildFilter:
      paths:
        - client/**